# # Instruction
# - assign a new image name
# - make this file consistent with that in https://github.com/okatsn/MyTeXLife

services:
  # The service name should be consistent with that in devcontainer.json
  devojs:
    build:
      context: ..
      #     That is out of /.devcontainer
      # context: .
      #     That is /.devcontainer
      dockerfile: .devcontainer/Dockerfile

    # Better not to have duplicate image name
    image: playojs 
    init: true 
    # See https://docs.docker.com/compose/compose-file/compose-file-v3/#init
    
    # Better not to have duplicate container name. Error "Conflict will occur if another. The container name "/tex-with-julia" is already in use by container" might occur if there is another container of the same name is currently running.
    container_name: my-ojs-playground
    privileged: true  # Add this line to allow Docker operations (using `docker` via dind)
    volumes:
      # # The home directory is called "workspace"; try `cd ..` and `ls` to figure it out.
      - ..:/home/jovyan/workspace
      # # Docker socket to access Docker server
      - /var/run/docker.sock:/var/run/docker.sock
      # # SSH directory
      - ~/.ssh:/home/jovyan/.ssh
      # For Windows without WSL, a copy will be made from /tmp/.ssh to ~/.ssh to fix permissions
      # - ~/.ssh:/tmp/.ssh:ro
      # # Git config
      - ~/.gitconfig:/home/jovyan/.gitconfig
      - vscode-server:/home/jovyan/.vscode-server
      # # DVC credential cache directory (this makes DVC credential persistant)
      - ~/.cache/pydrive2fs:/home/jovyan/.cache/pydrive2fs
    environment:
      # Set time zone (GMT-8 is UTC+8):
      # - To print available time-zone names: ls /usr/share/zoneinfo
      - TZ=Etc/GMT-8
    entrypoint: sh -c "sleep infinity"

    
# KEYNOTE: Those defined volumes in service should be declared in the root level
# Unbind vscode-server to volumes to ensure extensions in devcontainer.json to be installed on rebuild
volumes:
  vscode-server: