name: Example workflow to be triggered by Repo A

on:
  repository_dispatch:
    types: [push-from-repo-a] # Must match the event_type sent from Repo A

jobs:
  your-job-name:
    runs-on: ubuntu-latest
    steps:
      - name: Show Payload (if sent)
        run: |
          echo "Triggered by Repo A"
          echo "Payload:"
          echo "${{ github.event.client_payload }}"
