

services:
  myservice:
    image: jbuild
    # env_file:
    #   - my-build.env
    # # KEYNOTE: `env_file` option cannot take files not exactly in the root project directory (where docker-compose.yml resides). 
    # Please use `--env-file` option.
    # See https://docs.docker.com/compose/environment-variables/set-environment-variables/#substitute-with-an-env-file
    # https://docs.docker.com/compose/environment-variables/set-environment-variables/#substitute-with---env-file
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NB_UID=${NB_UID}
        - NB_GID=${NB_GID}
        - DEBIAN_VERSION=${DEBIAN_VERSION}
    entrypoint: sh -c "sleep infinity"