

services:
  myservice:
    image: jtexworkspace
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NB_UID=${NB_UID}
        - NB_GID=${NB_GID}
        - DEBIAN_VERSION=${DEBIAN_VERSION}
    entrypoint: sh -c "sleep infinity"