# This is [Compose file](https://docs.docker.com/compose/compose-file/compose-file-v3/)
# Please refer okatsn/MyJuliaSpace for more information
version: '3'

services:
  devjq:
    # service name is arbitrary
    image: my-quarto-space
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VSCODE_PATH: /home/jovyan/.vscode-server
        VSCODE_INSIDER_PATH: /home/jovyan/.vscode-server-insiders
    init: true
    container_name: my-quarto-space
    environment:
      - TZ=Asia/Taipei
    volumes:
      - ..:/home/jovyan/devspace
      # Persistent the julia depot
      - julia-depot:/home/jovyan/.julia
      # KEYNOTE: make sure /home/$NB_USER/.vscode-server/extensions is `mkdir`ed in Dockerfile
      # KEYNOTE: .vscode-server should not exist in the image to be pushed
      # - If the entire .vscode-server directories does not be added to volumes, such as the case that only .vscode-server/extensions is added to volumes, in the later stage from this image (FROM okatsn/my-julia-space) cannot have their customized vscode extensions in devcontainer.json successfully setup.
      - vscode-server:/home/jovyan/.vscode-server
      - vscode-server-insiders:/home/jovyan/.vscode-server-insiders
    command:
      - sh
      - -c
      - sleep infinity
      # - julia --project=@. -e 'using Pkg; Pkg.build("IJulia")'; sleep infinity
      # KEYNOTE:
      # - Use semi-colon to separate command
      # - build IJulia everytime is nonsense. IJulia should be built when it is installed in a certain environment. See https://pkgdocs.julialang.org/v1/managing-packages/#Building-packages
      # - `Render` error may occur due to the followings:
      #   - It is not `instantiate`d in the opening project.
      #   - It is not `precompile`d in the opening project.
      #   - These are the reasons that cause julia kernel died.
      # - `Pkg.build("IJulia")` is required only for [Updating Julia and IJulia](https://julialang.github.io/IJulia.jl/stable/manual/installation/#Updating-Julia-and-IJulia)

volumes:
  # KEYNOTE: Those defined volumes in service should be declared in the root level
  # - vscode-server are binded because I don't want them be in the image (which might cause permission issues when FROM my-julia-space that a new set of extensions is intended to be installed in container building stage)
  # - Don't bind vscode-server if you like your container has extensions installed as prescripted in devcontainer.json
  julia-depot:
  vscode-server:
  vscode-server-insiders:
