FROM okatsn/my-mini-explorer:latest

# Add any project-specific tools or configurations below.
# Example: install additional apt packages
# RUN apt-get update && apt-get install -y \
#     your-package \
#     && rm -rf /var/lib/apt/lists/*


## Install Starship
## Starship configuration
ARG NB_USER

USER $NB_USER